/**
 * Legal PDF Generator
 *
 * Generates court-standard legal documents as real PDF files using pdf-lib.
 * Supports motions, briefs, demand letters, court filings, and contracts.
 * All documents follow proper legal formatting: caption, case number,
 * numbered paragraphs, signature blocks, certificate of service.
 */

import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont, degrees } from "pdf-lib";

// ── Types ──

export type DocumentType =
  | "motion_to_dismiss"
  | "motion_to_suppress"
  | "motion_for_discovery"
  | "motion_for_continuance"
  | "demand_letter"
  | "legal_brief"
  | "cease_and_desist"
  | "affidavit"
  | "notice_of_appearance"
  | "memorandum_of_law";

export interface DocumentRequest {
  type: DocumentType;
  matterId: string;
  caseCaption: string;        // e.g. "STATE OF FLORIDA v. [DEFENDANT]"
  caseNumber: string;         // e.g. "2026-CF-001234"
  court: string;              // e.g. "CIRCUIT COURT OF THE EIGHTEENTH JUDICIAL CIRCUIT"
  jurisdiction: string;       // e.g. "IN AND FOR SEMINOLE COUNTY, FLORIDA"
  movingParty: string;        // "Defendant" or "Plaintiff"
  aiDraftedContent: string;   // The AI-generated body from the agent
  agentName: string;          // Which agent drafted it
  confidenceScore: number;
  generatedAt: string;
  attorneyName?: string;      // Name for signature block (personalized downloads)
}

export interface GeneratedDocument {
  id: string;
  type: DocumentType;
  matterId: string;
  pdfBytes: Uint8Array;
  filename: string;
  pageCount: number;
  generatedAt: string;
  agentName: string;
  confidenceScore: number;
  disclaimer: string;
}

// ── Document Labels ──

const DOCUMENT_LABELS: Record<DocumentType, string> = {
  motion_to_dismiss: "MOTION TO DISMISS",
  motion_to_suppress: "MOTION TO SUPPRESS EVIDENCE",
  motion_for_discovery: "MOTION FOR DISCOVERY",
  motion_for_continuance: "MOTION FOR CONTINUANCE",
  demand_letter: "DEMAND LETTER",
  legal_brief: "LEGAL BRIEF",
  cease_and_desist: "CEASE AND DESIST",
  affidavit: "AFFIDAVIT",
  notice_of_appearance: "NOTICE OF APPEARANCE",
  memorandum_of_law: "MEMORANDUM OF LAW",
};

// ── Layout Constants ──

const MARGIN_LEFT = 72;      // 1 inch
const MARGIN_RIGHT = 72;
const MARGIN_TOP = 72;
const MARGIN_BOTTOM = 90;
const LINE_HEIGHT = 14;
const PARA_SPACING = 8;
const PAGE_WIDTH = 612;      // Letter size
const PAGE_HEIGHT = 792;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

// ── Colors ──

const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.45, 0.45, 0.45);
const WATERMARK = rgb(0.92, 0.92, 0.92);

// ── PDF Generation ──

export async function generateLegalPDF(req: DocumentRequest): Promise<GeneratedDocument> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${DOCUMENT_LABELS[req.type]} — ${req.caseNumber}`);
  pdf.setAuthor("UNYKORN Law — AI Legal Platform");
  pdf.setSubject(req.caseCaption);
  pdf.setCreator("UNYKORN Legal Document System v2.0");
  pdf.setProducer("pdf-lib");
  pdf.setCreationDate(new Date(req.generatedAt));

  const timesRoman = await pdf.embedFont(StandardFonts.TimesRoman);
  const timesBold = await pdf.embedFont(StandardFonts.TimesRomanBold);
  const timesItalic = await pdf.embedFont(StandardFonts.TimesRomanItalic);
  const courier = await pdf.embedFont(StandardFonts.Courier);

  const ctx: DrawContext = {
    pdf, timesRoman, timesBold, timesItalic, courier,
    currentPage: pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
    y: PAGE_HEIGHT - MARGIN_TOP,
    pageCount: 1,
  };

  // ── Draw Document ──
  drawCaption(ctx, req);
  drawDocumentTitle(ctx, req);
  drawBody(ctx, req);
  drawSignatureBlock(ctx, req);
  drawCertificateOfService(ctx, req);
  drawDisclaimer(ctx);

  // Add page numbers to all pages
  const pages = pdf.getPages();
  for (let i = 0; i < pages.length; i++) {
    const pg = pages[i];
    const text = `Page ${i + 1} of ${pages.length}`;
    const w = timesRoman.widthOfTextAtSize(text, 9);
    pg.drawText(text, { x: PAGE_WIDTH / 2 - w / 2, y: 36, size: 9, font: timesRoman, color: GRAY });

    // DRAFT watermark
    drawWatermark(pg, timesBold);
  }

  const pdfBytes = await pdf.save();
  const filename = `${req.type.replace(/_/g, "-")}-${req.caseNumber.replace(/[^a-zA-Z0-9-]/g, "")}-${Date.now()}.pdf`;

  return {
    id: `doc-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    type: req.type,
    matterId: req.matterId,
    pdfBytes,
    filename,
    pageCount: pages.length,
    generatedAt: req.generatedAt,
    agentName: req.agentName,
    confidenceScore: req.confidenceScore,
    disclaimer: "AI-GENERATED DRAFT — NOT FOR FILING. This document was generated by an AI agent and must be reviewed by a licensed attorney before submission to any court or opposing party.",
  };
}

// ── Drawing Context ──

interface DrawContext {
  pdf: PDFDocument;
  timesRoman: PDFFont;
  timesBold: PDFFont;
  timesItalic: PDFFont;
  courier: PDFFont;
  currentPage: PDFPage;
  y: number;
  pageCount: number;
}

function ensureSpace(ctx: DrawContext, needed: number) {
  if (ctx.y - needed < MARGIN_BOTTOM) {
    ctx.currentPage = ctx.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    ctx.y = PAGE_HEIGHT - MARGIN_TOP;
    ctx.pageCount++;
  }
}

// ── Caption Block ──

function drawCaption(ctx: DrawContext, req: DocumentRequest) {
  const { currentPage: pg, timesBold, timesRoman, timesItalic } = ctx;

  // Court name
  drawCenteredText(pg, req.court, timesBold, 11, ctx.y, BLACK);
  ctx.y -= LINE_HEIGHT + 2;
  drawCenteredText(pg, req.jurisdiction, timesRoman, 10, ctx.y, BLACK);
  ctx.y -= LINE_HEIGHT + 12;

  // Caption box
  const captionParts = req.caseCaption.split(" v. ");
  const plaintiff = captionParts[0] || "PLAINTIFF";
  const defendant = captionParts[1] || "DEFENDANT";

  // Left side — parties
  const boxTop = ctx.y;
  pg.drawText(plaintiff + ",", { x: MARGIN_LEFT + 20, y: ctx.y, size: 11, font: timesBold, color: BLACK });
  ctx.y -= LINE_HEIGHT + 4;

  const movingLabel = req.movingParty === "Defendant" ? "Plaintiff" : "Moving Party";
  pg.drawText(`          ${movingLabel},`, { x: MARGIN_LEFT + 20, y: ctx.y, size: 10, font: timesItalic, color: BLACK });
  ctx.y -= LINE_HEIGHT + 8;

  pg.drawText("     v.", { x: MARGIN_LEFT + 20, y: ctx.y, size: 11, font: timesBold, color: BLACK });
  ctx.y -= LINE_HEIGHT + 8;

  pg.drawText(defendant + ",", { x: MARGIN_LEFT + 20, y: ctx.y, size: 11, font: timesBold, color: BLACK });
  ctx.y -= LINE_HEIGHT + 4;

  const defLabel = req.movingParty === "Defendant" ? "Defendant / Movant" : "Respondent";
  pg.drawText(`          ${defLabel}.`, { x: MARGIN_LEFT + 20, y: ctx.y, size: 10, font: timesItalic, color: BLACK });
  ctx.y -= LINE_HEIGHT;

  const boxBottom = ctx.y;

  // Center divider line
  const divX = PAGE_WIDTH / 2;
  pg.drawLine({ start: { x: divX, y: boxTop + 8 }, end: { x: divX, y: boxBottom - 4 }, thickness: 0.5, color: BLACK });

  // Right side — case identifiers
  const rightX = divX + 20;
  let ry = boxTop;
  pg.drawText("Case No.:", { x: rightX, y: ry, size: 10, font: timesRoman, color: BLACK });
  pg.drawText(req.caseNumber, { x: rightX + 55, y: ry, size: 10, font: timesBold, color: BLACK });
  ry -= LINE_HEIGHT + 8;

  pg.drawText("Division:", { x: rightX, y: ry, size: 10, font: timesRoman, color: BLACK });
  pg.drawText("CRIMINAL", { x: rightX + 55, y: ry, size: 10, font: timesRoman, color: BLACK });
  ry -= LINE_HEIGHT + 12;

  pg.drawText(DOCUMENT_LABELS[req.type], { x: rightX, y: ry, size: 10, font: timesBold, color: BLACK });

  // Horizontal rules
  pg.drawLine({ start: { x: MARGIN_LEFT, y: boxTop + 12 }, end: { x: PAGE_WIDTH - MARGIN_RIGHT, y: boxTop + 12 }, thickness: 1, color: BLACK });
  pg.drawLine({ start: { x: MARGIN_LEFT, y: boxBottom - 8 }, end: { x: PAGE_WIDTH - MARGIN_RIGHT, y: boxBottom - 8 }, thickness: 1, color: BLACK });

  ctx.y = boxBottom - 24;
}

// ── Document Title ──

function drawDocumentTitle(ctx: DrawContext, req: DocumentRequest) {
  const title = DOCUMENT_LABELS[req.type];
  drawCenteredText(ctx.currentPage, title, ctx.timesBold, 14, ctx.y, BLACK);
  ctx.y -= LINE_HEIGHT + 6;
  drawCenteredLine(ctx.currentPage, ctx.y + 4, 200, 0.5);
  ctx.y -= 16;
}

// ── Body Content ──

function drawBody(ctx: DrawContext, req: DocumentRequest) {
  // Opening
  const intro = req.movingParty === "Defendant"
    ? `COMES NOW the Defendant, by and through undersigned counsel, and respectfully moves this Honorable Court to enter an Order granting the relief requested herein, and in support thereof states as follows:`
    : `COMES NOW the ${req.movingParty}, and respectfully submits this ${DOCUMENT_LABELS[req.type].toLowerCase()} to this Honorable Court, and in support thereof states as follows:`;

  drawWrappedText(ctx, intro, ctx.timesRoman, 11, LINE_HEIGHT, BLACK);
  ctx.y -= PARA_SPACING * 2;

  // AI-generated content — split into paragraphs, number them
  const paragraphs = req.aiDraftedContent
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  let paraNum = 1;
  for (const para of paragraphs) {
    ensureSpace(ctx, LINE_HEIGHT * 3);

    // Check if paragraph starts with a heading-like pattern (all caps or Roman numerals)
    const isHeading = /^(I{1,3}V?|V?I{0,3})\.\s|^[A-Z][A-Z\s]{4,}$/.test(para);
    if (isHeading) {
      ctx.y -= PARA_SPACING;
      drawWrappedText(ctx, para, ctx.timesBold, 11, LINE_HEIGHT, BLACK);
      ctx.y -= PARA_SPACING;
      continue;
    }

    // Numbered paragraph
    const numText = `${paraNum}.`;
    ctx.currentPage.drawText(numText, { x: MARGIN_LEFT + 24, y: ctx.y, size: 11, font: ctx.timesBold, color: BLACK });

    const savedX = MARGIN_LEFT;
    const indent = 48;
    drawWrappedTextIndented(ctx, para, ctx.timesRoman, 11, LINE_HEIGHT, BLACK, indent);
    ctx.y -= PARA_SPACING;
    paraNum++;
  }

  // Closing — WHEREFORE
  ctx.y -= PARA_SPACING;
  ensureSpace(ctx, LINE_HEIGHT * 6);

  const wherefore = `WHEREFORE, the ${req.movingParty} respectfully requests that this Honorable Court grant the relief sought herein, and grant any other relief this Court deems just and proper.`;
  drawWrappedText(ctx, wherefore, ctx.timesBold, 11, LINE_HEIGHT, BLACK);
  ctx.y -= PARA_SPACING * 2;
}

// ── Signature Block ──

function drawSignatureBlock(ctx: DrawContext, req: DocumentRequest) {
  ensureSpace(ctx, 120);
  ctx.y -= 12;

  const rightCol = PAGE_WIDTH / 2 + 20;

  ctx.currentPage.drawText("Respectfully submitted,", { x: rightCol, y: ctx.y, size: 11, font: ctx.timesItalic, color: BLACK });
  ctx.y -= LINE_HEIGHT * 3;

  // Signature line
  ctx.currentPage.drawLine({ start: { x: rightCol, y: ctx.y + 2 }, end: { x: rightCol + 200, y: ctx.y + 2 }, thickness: 0.5, color: BLACK });
  ctx.y -= LINE_HEIGHT + 2;

  const attyDisplay = req.attorneyName ? `${req.attorneyName}, Esq.` : "[Attorney Name, Esq.]";
  ctx.currentPage.drawText(attyDisplay, { x: rightCol, y: ctx.y, size: 10, font: ctx.timesRoman, color: BLACK });
  ctx.y -= LINE_HEIGHT;
  ctx.currentPage.drawText("Florida Bar No. [TBD]", { x: rightCol, y: ctx.y, size: 10, font: ctx.timesRoman, color: BLACK });
  ctx.y -= LINE_HEIGHT;
  ctx.currentPage.drawText("UNYKORN Law", { x: rightCol, y: ctx.y, size: 10, font: ctx.timesBold, color: BLACK });
  ctx.y -= LINE_HEIGHT;
  ctx.currentPage.drawText(`Counsel for ${req.movingParty}`, { x: rightCol, y: ctx.y, size: 10, font: ctx.timesRoman, color: BLACK });
  ctx.y -= LINE_HEIGHT * 2;

  // Date line
  ctx.currentPage.drawText(`Date: ${new Date(req.generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, {
    x: rightCol, y: ctx.y, size: 10, font: ctx.timesRoman, color: BLACK,
  });
  ctx.y -= LINE_HEIGHT * 2;
}

// ── Certificate of Service ──

function drawCertificateOfService(ctx: DrawContext, req: DocumentRequest) {
  ensureSpace(ctx, 80);

  drawCenteredText(ctx.currentPage, "CERTIFICATE OF SERVICE", ctx.timesBold, 11, ctx.y, BLACK);
  ctx.y -= LINE_HEIGHT + 6;

  const certText = `I HEREBY CERTIFY that on ${new Date(req.generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}, a true and correct copy of the foregoing was furnished to all parties of record by [method of service].`;
  drawWrappedText(ctx, certText, ctx.timesRoman, 10, LINE_HEIGHT - 1, BLACK);
  ctx.y -= LINE_HEIGHT * 3;

  const rightCol = PAGE_WIDTH / 2 + 20;
  ctx.currentPage.drawLine({ start: { x: rightCol, y: ctx.y + 2 }, end: { x: rightCol + 200, y: ctx.y + 2 }, thickness: 0.5, color: BLACK });
  ctx.y -= LINE_HEIGHT;
  const certAtty = req.attorneyName ? `${req.attorneyName}, Esq.` : "[Attorney Name, Esq.]";
  ctx.currentPage.drawText(certAtty, { x: rightCol, y: ctx.y, size: 10, font: ctx.timesRoman, color: BLACK });
  ctx.y -= LINE_HEIGHT * 2;
}

// ── AI Disclaimer Footer ──

function drawDisclaimer(ctx: DrawContext) {
  ensureSpace(ctx, 60);
  ctx.y -= 12;

  const line1 = "AI-GENERATED DRAFT — NOT FOR FILING";
  const line2 = "This document was drafted by UNYKORN AI Agent and requires licensed attorney review before any submission.";
  const line3 = `Confidence Score: N/A  |  Generated: ${new Date().toISOString()}  |  UNYKORN Law Platform v2.0`;

  drawCenteredText(ctx.currentPage, line1, ctx.timesBold, 8, ctx.y, GRAY);
  ctx.y -= 10;
  drawCenteredText(ctx.currentPage, line2, ctx.timesItalic, 7, ctx.y, GRAY);
  ctx.y -= 10;
  drawCenteredText(ctx.currentPage, line3, ctx.courier, 6.5, ctx.y, GRAY);
}

// ── DRAFT Watermark ──

function drawWatermark(page: PDFPage, font: PDFFont) {
  const text = "DRAFT";
  const size = 72;
  const w = font.widthOfTextAtSize(text, size);
  page.drawText(text, {
    x: PAGE_WIDTH / 2 - w / 2,
    y: PAGE_HEIGHT / 2 - 20,
    size,
    font,
    color: WATERMARK,
    opacity: 0.15,
    rotate: degrees(-45),
  });
}

// ── Text Utilities ──

function drawCenteredText(page: PDFPage, text: string, font: PDFFont, size: number, y: number, color: ReturnType<typeof rgb>) {
  const w = font.widthOfTextAtSize(text, size);
  page.drawText(text, { x: PAGE_WIDTH / 2 - w / 2, y, size, font, color });
}

function drawCenteredLine(page: PDFPage, y: number, width: number, thickness: number) {
  page.drawLine({
    start: { x: PAGE_WIDTH / 2 - width / 2, y },
    end: { x: PAGE_WIDTH / 2 + width / 2, y },
    thickness,
    color: BLACK,
  });
}

function drawWrappedText(ctx: DrawContext, text: string, font: PDFFont, size: number, lineH: number, color: ReturnType<typeof rgb>) {
  drawWrappedTextIndented(ctx, text, font, size, lineH, color, 0);
}

function drawWrappedTextIndented(ctx: DrawContext, text: string, font: PDFFont, size: number, lineH: number, color: ReturnType<typeof rgb>, indent: number) {
  const maxWidth = CONTENT_WIDTH - indent;
  const words = text.split(/\s+/);
  let line = "";

  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(test, size) > maxWidth && line) {
      ensureSpace(ctx, lineH);
      ctx.currentPage.drawText(line, { x: MARGIN_LEFT + indent, y: ctx.y, size, font, color });
      ctx.y -= lineH;
      line = word;
    } else {
      line = test;
    }
  }
  if (line) {
    ensureSpace(ctx, lineH);
    ctx.currentPage.drawText(line, { x: MARGIN_LEFT + indent, y: ctx.y, size, font, color });
    ctx.y -= lineH;
  }
}

// ── Document Type Metadata ──

export function getDocumentTypes(): Array<{ type: DocumentType; label: string; description: string; category: string }> {
  return [
    { type: "motion_to_dismiss", label: "Motion to Dismiss", description: "Request to dismiss charges or claims for legal insufficiency", category: "motion" },
    { type: "motion_to_suppress", label: "Motion to Suppress", description: "Motion to exclude illegally obtained evidence", category: "motion" },
    { type: "motion_for_discovery", label: "Motion for Discovery", description: "Compel production of documents and evidence", category: "motion" },
    { type: "motion_for_continuance", label: "Motion for Continuance", description: "Request postponement of hearing or trial date", category: "motion" },
    { type: "demand_letter", label: "Demand Letter", description: "Formal demand for payment, action, or resolution", category: "correspondence" },
    { type: "legal_brief", label: "Legal Brief", description: "Written legal argument with case law analysis", category: "brief" },
    { type: "cease_and_desist", label: "Cease & Desist", description: "Notice demanding immediate cessation of specific activity", category: "correspondence" },
    { type: "affidavit", label: "Affidavit", description: "Sworn statement of facts under oath", category: "filing" },
    { type: "notice_of_appearance", label: "Notice of Appearance", description: "Formal notice that counsel will represent a party", category: "filing" },
    { type: "memorandum_of_law", label: "Memorandum of Law", description: "Detailed legal analysis and argument in support of a position", category: "brief" },
  ];
}
