import { NextResponse } from 'next/server';

function generateDemandLetter(data: {
  senderName: string; senderAddress: string;
  recipientName: string; recipientAddress: string;
  issueType: string; amount: string; facts: string;
  resolution: string; deadline: string;
}): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const issueLabels: Record<string, string> = {
    'unpaid-invoice': 'Unpaid Invoice',
    'breach-of-contract': 'Breach of Contract',
    'payment-dispute': 'Payment Dispute',
    'property-damage': 'Property Damage',
    'other': 'Legal Matter',
  };
  const issueLabel = issueLabels[data.issueType] || 'Legal Matter';

  return `DEMAND LETTER

${today}

VIA CERTIFIED MAIL — RETURN RECEIPT REQUESTED

${data.recipientName}
${data.recipientAddress}

Re: ${issueLabel} — Demand for Payment of $${data.amount}

Dear ${data.recipientName},

I am writing to formally demand resolution of the following matter. Please treat this correspondence with the urgency it deserves.

STATEMENT OF FACTS

${data.facts}

DEMAND

Based on the foregoing facts, I hereby demand the following:

${data.resolution}

DEADLINE

This demand must be satisfied on or before ${data.deadline}. Failure to respond or comply by this date may result in further legal action without additional notice.

AMOUNT IN DISPUTE: $${data.amount}

Please direct all correspondence regarding this matter to the undersigned at the address below.

Sincerely,

${data.senderName}
${data.senderAddress}

---
Generated by UNYKORN // LAW — AI Legal Intelligence Platform
This document is a template and does not constitute legal advice.`;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { senderName, senderAddress, recipientName, recipientAddress, issueType, amount, facts, resolution, deadline } = body;
    if (!senderName || !recipientName || !amount || !facts || !resolution || !deadline) {
      return NextResponse.json({ ok: false, error: 'Missing required fields' }, { status: 400 });
    }
    const letterId = `DL-${Date.now().toString(36).toUpperCase()}`;
    const content = generateDemandLetter(body);
    return NextResponse.json({
      ok: true,
      letterId,
      content,
      status: 'draft',
      message: 'Letter generated',
    });
  } catch {
    return NextResponse.json({ ok: false, error: 'Invalid request' }, { status: 400 });
  }
}
