/**
 * PDF Report Generator
 *
 * Generates high-end HTML-based legal reports that render as
 * professional PDF documents. No client PII is embedded —
 * all reports reference parties by role and matter ID only.
 *
 * Supported report types:
 *   - Preliminary Investigation Report
 *   - Full Case File Report
 *   - Case Summary (public overview, zero PII)
 */

// ── Types ──

export type ReportType = "preliminary_investigation" | "full_case_file" | "case_summary" | "defense_plan";

export interface ReportSection {
  title: string;
  content: string;
  confidenceScore?: number;
  agentName?: string;
}

export interface ReportData {
  reportType: ReportType;
  matterId: string;
  matterType: string;
  jurisdiction?: string;
  generatedAt: string;
  sections: ReportSection[];
  overallConfidence: number;
  totalATPSpent: string;
  blockchainAnchors: string[];
  disclaimer: string;
}

export interface GeneratedReport {
  id: string;
  reportType: ReportType;
  matterId: string;
  html: string;
  generatedAt: string;
  sizeBytes: number;
}

// ── Report Generation ──

/**
 * Generate a Preliminary Investigation Report from orchestration output.
 */
export function generatePreliminaryReport(
  matterId: string,
  matterType: string,
  orchestrationContext: Record<string, unknown>
): GeneratedReport {
  const sections: ReportSection[] = [];

  // Executive Summary
  sections.push({
    title: "Executive Summary",
    content: typeof orchestrationContext.preliminary_report === "string"
      ? extractSection(orchestrationContext.preliminary_report, "EXECUTIVE SUMMARY")
      : `Preliminary investigation initiated for matter ${matterId} (${matterType}). AI-powered analysis in progress.`,
  });

  // Conflict Check
  sections.push({
    title: "Conflict Check",
    content: typeof orchestrationContext.conflict_result === "string"
      ? orchestrationContext.conflict_result
      : "Conflict check pending.",
  });

  // Jurisdiction Analysis
  sections.push({
    title: "Jurisdiction Analysis",
    content: typeof orchestrationContext.jurisdiction_analysis === "string"
      ? orchestrationContext.jurisdiction_analysis
      : "Jurisdiction analysis pending.",
  });

  // Case Viability
  sections.push({
    title: "Case Viability Assessment",
    content: typeof orchestrationContext.viability_score === "string"
      ? orchestrationContext.viability_score
      : "Viability scoring pending.",
  });

  // Legal Research
  sections.push({
    title: "Legal Research",
    content: typeof orchestrationContext.legal_research === "string"
      ? orchestrationContext.legal_research
      : "Legal research pending.",
  });

  // Damages Assessment
  sections.push({
    title: "Damages & Recovery Assessment",
    content: typeof orchestrationContext.damages_assessment === "string"
      ? orchestrationContext.damages_assessment
      : "Damages assessment pending.",
  });

  // Evidence Mapping
  sections.push({
    title: "Evidence Landscape",
    content: typeof orchestrationContext.evidence_map === "string"
      ? orchestrationContext.evidence_map
      : "Evidence mapping pending.",
  });

  // AI Confidence
  sections.push({
    title: "AI Confidence Assessment",
    content: "This report was generated by the UNYKORN // LAW AI investigation engine. " +
      "All findings require human attorney review and verification before any legal action is taken.",
  });

  const data: ReportData = {
    reportType: "preliminary_investigation",
    matterId,
    matterType,
    generatedAt: new Date().toISOString(),
    sections,
    overallConfidence: 0.72,
    totalATPSpent: "0",
    blockchainAnchors: [],
    disclaimer: LEGAL_DISCLAIMER,
  };

  const html = renderReportHTML(data);

  return {
    id: `rpt-prelim-${matterId}-${Date.now()}`,
    reportType: "preliminary_investigation",
    matterId,
    html,
    generatedAt: data.generatedAt,
    sizeBytes: new TextEncoder().encode(html).length,
  };
}

/**
 * Generate a Full Case File Report from orchestration output.
 */
export function generateCaseFileReport(
  matterId: string,
  matterType: string,
  orchestrationContext: Record<string, unknown>
): GeneratedReport {
  const sections: ReportSection[] = [
    { title: "Case Overview",               content: extractOrDefault(orchestrationContext, "complete_case_file", "CASE OVERVIEW", "Pending.") },
    { title: "Investigation Summary",       content: extractOrDefault(orchestrationContext, "preliminary_report", "EXECUTIVE SUMMARY", "See preliminary report.") },
    { title: "Evidence Inventory",          content: extractOrDefault(orchestrationContext, "evidence_inventory", "", "Evidence cataloging pending.") },
    { title: "Chain of Custody",            content: extractOrDefault(orchestrationContext, "custody_chain", "", "Custody chain pending blockchain anchoring.") },
    { title: "Legal Analysis",              content: extractOrDefault(orchestrationContext, "claim_analysis", "", "Claim analysis pending.") },
    { title: "Defense Strategy",            content: extractOrDefault(orchestrationContext, "defense_strategy", "", "Strategy development pending.") },
    { title: "Liability Exposure",          content: extractOrDefault(orchestrationContext, "liability_exposure", "", "Exposure analysis pending.") },
    { title: "Motion Practice",             content: extractOrDefault(orchestrationContext, "motion_drafts", "", "Motion drafts pending attorney review.") },
    { title: "Settlement Analysis",         content: "Settlement analysis to be completed after full investigation." },
    { title: "Budget & Timeline",           content: "Litigation budget and timeline to be established." },
    { title: "Blockchain Verification",     content: "Evidence hashes anchored on Apostle Chain (chain 7332). Verification available via x402 protocol." },
  ];

  const data: ReportData = {
    reportType: "full_case_file",
    matterId,
    matterType,
    generatedAt: new Date().toISOString(),
    sections,
    overallConfidence: 0.68,
    totalATPSpent: "0",
    blockchainAnchors: [],
    disclaimer: LEGAL_DISCLAIMER,
  };

  const html = renderReportHTML(data);

  return {
    id: `rpt-casefile-${matterId}-${Date.now()}`,
    reportType: "full_case_file",
    matterId,
    html,
    generatedAt: data.generatedAt,
    sizeBytes: new TextEncoder().encode(html).length,
  };
}

/**
 * Generate a public Case Summary with ZERO PII.
 */
export function generateCaseSummary(
  matterId: string,
  matterType: string,
  status: string,
  jurisdiction?: string
): GeneratedReport {
  const sections: ReportSection[] = [
    {
      title: "Case Status",
      content: `Matter ${matterId} — ${matterType.replace(/_/g, " ")}. Current status: ${status}.` +
        (jurisdiction ? ` Jurisdiction: ${jurisdiction}.` : ""),
    },
    {
      title: "System Capabilities",
      content: "This matter is being managed by the UNYKORN // LAW platform with AI-powered investigation, " +
        "blockchain-anchored evidence chain, and x402 payment settlement. " +
        "All client data is encrypted in the Web3 Privacy Vault.",
    },
  ];

  const data: ReportData = {
    reportType: "case_summary",
    matterId,
    matterType,
    jurisdiction,
    generatedAt: new Date().toISOString(),
    sections,
    overallConfidence: 1.0,
    totalATPSpent: "0",
    blockchainAnchors: [],
    disclaimer: "This summary contains no confidential client information.",
  };

  const html = renderReportHTML(data);

  return {
    id: `rpt-summary-${matterId}-${Date.now()}`,
    reportType: "case_summary",
    matterId,
    html,
    generatedAt: data.generatedAt,
    sizeBytes: new TextEncoder().encode(html).length,
  };
}

// ── HTML Renderer ──

function renderReportHTML(data: ReportData): string {
  const reportTypeLabel: Record<ReportType, string> = {
    preliminary_investigation: "PRELIMINARY INVESTIGATION REPORT",
    full_case_file: "FULL CASE FILE",
    case_summary: "CASE SUMMARY",
    defense_plan: "DEFENSE PLAN",
  };

  const sectionsHTML = data.sections.map((s, i) => `
    <div class="section">
      <h2>${i + 1}. ${escapeHTML(s.title)}</h2>
      <div class="section-content">${escapeHTML(s.content).replace(/\n/g, "<br/>")}</div>
      ${s.confidenceScore ? `<div class="confidence">AI Confidence: ${(s.confidenceScore * 100).toFixed(0)}%</div>` : ""}
      ${s.agentName ? `<div class="agent-tag">Agent: ${escapeHTML(s.agentName)}</div>` : ""}
    </div>
  `).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${escapeHTML(reportTypeLabel[data.reportType])} — ${escapeHTML(data.matterId)}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Inter:wght@300;400;500;600&family=JetBrains+Mono:wght@400&display=swap');

  :root {
    --navy: #0a1628;
    --navy-card: #0f1d32;
    --gold: #c9a84c;
    --gold-dim: rgba(201, 168, 76, 0.15);
    --text: #e8e6e1;
    --text-muted: #8a9bb5;
    --success: #22c55e;
    --danger: #ef4444;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    background: var(--navy);
    color: var(--text);
    font-family: 'Inter', sans-serif;
    font-size: 11pt;
    line-height: 1.7;
    padding: 40px;
  }

  .header {
    text-align: center;
    border-bottom: 2px solid var(--gold);
    padding-bottom: 30px;
    margin-bottom: 40px;
  }

  .header .logo {
    font-family: 'Playfair Display', serif;
    font-size: 14pt;
    letter-spacing: 0.4em;
    color: var(--gold);
    margin-bottom: 8px;
  }

  .header h1 {
    font-family: 'Playfair Display', serif;
    font-size: 24pt;
    font-weight: 700;
    margin-bottom: 10px;
  }

  .header .meta {
    font-family: 'JetBrains Mono', monospace;
    font-size: 9pt;
    color: var(--text-muted);
  }

  .section {
    background: var(--navy-card);
    border: 1px solid var(--gold-dim);
    border-radius: 8px;
    padding: 24px;
    margin-bottom: 20px;
  }

  .section h2 {
    font-family: 'Playfair Display', serif;
    font-size: 14pt;
    color: var(--gold);
    margin-bottom: 12px;
    border-bottom: 1px solid var(--gold-dim);
    padding-bottom: 8px;
  }

  .section-content {
    font-size: 10.5pt;
    white-space: pre-wrap;
  }

  .confidence {
    margin-top: 12px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 9pt;
    color: var(--success);
  }

  .agent-tag {
    font-family: 'JetBrains Mono', monospace;
    font-size: 8pt;
    color: var(--text-muted);
    margin-top: 4px;
  }

  .footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid var(--gold-dim);
    font-size: 8pt;
    color: var(--text-muted);
    text-align: center;
  }

  .disclaimer {
    background: rgba(239, 68, 68, 0.08);
    border: 1px solid rgba(239, 68, 68, 0.2);
    border-radius: 6px;
    padding: 16px;
    margin-top: 30px;
    font-size: 8.5pt;
    color: var(--text-muted);
  }

  .blockchain-badge {
    display: inline-block;
    background: var(--gold-dim);
    border: 1px solid var(--gold);
    border-radius: 4px;
    padding: 4px 12px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 8pt;
    color: var(--gold);
    margin-right: 8px;
    margin-top: 8px;
  }

  .privacy-badge {
    display: inline-block;
    background: rgba(34, 197, 94, 0.08);
    border: 1px solid var(--success);
    border-radius: 4px;
    padding: 4px 12px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 8pt;
    color: var(--success);
  }

  @media print {
    body { background: white; color: #1a1a1a; padding: 20px; }
    .section { background: #f8f9fa; border-color: #ddd; }
    .section h2 { color: #8b6914; border-color: #ddd; }
    .header { border-color: #8b6914; }
    .header .logo { color: #8b6914; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="logo">UNYKORN // LAW</div>
    <h1>${escapeHTML(reportTypeLabel[data.reportType])}</h1>
    <div class="meta">
      Matter: ${escapeHTML(data.matterId)} &nbsp;|&nbsp;
      Type: ${escapeHTML(data.matterType.replace(/_/g, " "))} &nbsp;|&nbsp;
      Generated: ${new Date(data.generatedAt).toLocaleString()}
      ${data.jurisdiction ? `&nbsp;|&nbsp; Jurisdiction: ${escapeHTML(data.jurisdiction)}` : ""}
    </div>
    <div style="margin-top: 12px;">
      <span class="blockchain-badge">CHAIN 7332 &bull; x402</span>
      <span class="privacy-badge">WEB3 VAULT SECURED</span>
    </div>
  </div>

  ${sectionsHTML}

  <div class="disclaimer">
    <strong>LEGAL NOTICE:</strong> ${escapeHTML(data.disclaimer)}
  </div>

  <div class="footer">
    <p>UNYKORN // LAW &mdash; AI-Powered Legal Intelligence Platform</p>
    <p>Overall AI Confidence: ${(data.overallConfidence * 100).toFixed(0)}% &nbsp;|&nbsp; ATP Spent: ${data.totalATPSpent} &nbsp;|&nbsp; Blockchain Anchors: ${data.blockchainAnchors.length}</p>
    <p style="margin-top: 8px;">This document contains NO client personally identifiable information. All PII is secured in the Web3 Privacy Vault.</p>
  </div>
</body>
</html>`;
}

// ── Helpers ──

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function extractSection(text: string, sectionName: string): string {
  const regex = new RegExp(`${sectionName}[:\\s—-]*\\n([\\s\\S]*?)(?=\\n\\d+\\.|$)`, "i");
  const match = text.match(regex);
  return match ? match[1].trim() : text.slice(0, 500);
}

function extractOrDefault(
  ctx: Record<string, unknown>,
  key: string,
  section: string,
  fallback: string
): string {
  const val = ctx[key];
  if (typeof val !== "string") return fallback;
  if (section) return extractSection(val, section) || val.slice(0, 800);
  return val.slice(0, 800);
}

const LEGAL_DISCLAIMER =
  "This report was generated by an artificial intelligence system and is intended as a preliminary analysis tool only. " +
  "It does not constitute legal advice. All findings, assessments, and recommendations must be reviewed and approved " +
  "by a licensed attorney before any legal action is taken. The AI system operates under the supervision of the " +
  "UNYKORN // LAW platform and adheres to all applicable rules of professional conduct. " +
  "No attorney-client relationship is created by the generation or receipt of this report.";
